ljay79/jira-tools

Code.gs, dialogSettings.html, dialogs.gs, jiraApi.gs, jiraCommon.gs, jiraTicketInfo.gs, jsLib.gs, storage.gs
First unstyled but functional version right from google scripts.
=> Initial version

README.md, _config.yml
=> Set theme jekyll-theme-leap-day

Code.gs, IssueTable.gs, dialogIssuesFromFilter.html, dialogSettings.html, dialogs.gs, jiraApi.gs, jiraCommon.gs, jiraTicketInfo.gs, jsLib.gs, storage.gs
- new class IssueTable to create sheet listing for jira issues
- read all "my" filters including favourites
- define most common issue fields/columns with key name and header title
- extend unifyIssueAttrib() for simplified conversion of issue fields
- new HTML dialog model for picking filter and columns (styling missing)
- support POST for Jira REST api
=> Add feature to get issue list from filters

LICENSE, dialogAbout.html, dialogIssuesFromFilter.html, dialogSettings.html, dialogs.gs, jiraCommon.gs
=> DO Google UI

Code.gs, LICENSE, dialogAbout.html, dialogSettings.html, dialogs.gs, jiraApi.gs, jiraCommon.gs, jiraTicketInfo.gs, jsLib.gs, storage.gs
* Fix: Jira project key with numbers are ignored
* correct copyright placeholder
* Fix regexp for special chars within ticket status labels
* Jira URL now accepts http and https urls
=> Release v0.13.0

Code.gs, README.md, dialogAbout.html, dialogs.gs, jiraApi.gs, storage.gs
Release v0.14.0
BugFix for default columns from storage in latest release, was failing with "indexOf null" error
Feature: Added support for Jira Server version of grepping filters (only users favourite) vs. Jira OnDemand (all users filters + favourites)
=> v0.14.0 - GAS v8

Code.gs, dialogAbout.html, dialogs.gs, jiraCommon.gs
=> merge develop into master

dialogSettings.html, dialogTimesheet.html, dialogs.gs
@ljay79 ... the requested style update for your new features.
=> Fomatting and Styling for new dialog elements. Add date picker.

.gitignore, Code.gs, IssueTable.gs, README.md, dialogAbout.html, dialogSettings.html, dialogTimesheet.html, dialogWorklog.html, dialogs.gs, jiraApi.gs, jiraCommon.gs, jiraTicketInfo.gs, jsLib.gs, search.gs, storage.gs, userManager.gs, worklog.gs
Merge feature branch worklog back to develop
=> merge back feature branch

Code.gs, customFields.gs, storage.gs
=> #46 init jst_epic storage with default values

Code.gs, customFields.gs, dialogIssuesFromFilter.html, dialogSettings.html, dialogs.gs, jiraCommon.gs, search.gs, storage.gs, trigger.gs
Few enhancements and BugFixes,
solves issues: #47, #49 and #50
=> Merge latest fixes from develop

Code.gs, README.md, customFunctions.gs
=> little tweak

Code.gs, customFields.gs, dialogs.gs, jiraCommon.gs, userManager.gs
Finishing up the work on Version 1.
=> hardening, close branch as version 1.0.0

.gitignore, Code.gs, IssueTable.gs, jsLib.gs
1.0.4 BugFix; due to new sorting of table header it skipped/ignored and additional (custom) jira fields in the result
=> #102 - Bugfix missing custom columns on resulting list of issues from

README.md, src/Code.gs, src/IssueTable.gs, src/Storage.gs, src/customFields.gs, src/customFunctions.gs, src/dialogs.gs, src/jiraCommon.gs, src/jsLib.gs, src/search.gs, src/settings.gs, test/jiraApi.test.js, test/mocks/PropertiesService.js, test/settings.test.js
Didnt like the way to access storage through a getter method everytime, changed to object style.
=> Refactor storage access

src/Code.gs
- Fix for #173 - Has buggy sprint code
- Fixing up existing sprint (by ID functionality)
- Upgrade Storage class to latest version from https://github.com/gsuitedevs/apps-script-oauth2/blob/master/src/Storage.js
- Adding testing around the behavour of UserStorage before working on issieu #177
- Tidying up the splitting of user data to make more robust
- Add friendly error message for errors from PropertyService.getValue 
- schemaType stored in UserPropoerties for favourite fields - will help identify Sprint field uniquely
- Refactor and make all tests pass after adding customType
- Sprints field should now be indentified as readonly
- Parsing for Sprints passed back to JIRA uses new customType field. Sprint is still readonly.
=> Release version 1.2.1

src/jiraCommon.gs, src/models/jira/IssueFields.gs
Added support for Jira system fields versions (#187) and aggregatetimeoriginalestimate ("Affects Version/s" and "Σ Original Estimate")
=> #187 - add support for common Jira fields: versions and aggregatetimeoriginalestimate

src/Code.gs, src/models/gas/UserStorage.gs
=> fix issue #198

src/Code.gs, src/controllers/insertIssueTable.gs, src/models/IssueTableRendererDefault.gs
- #205; fix handling of IssueTable header definition from filter fields  …
- fix that vs this, use consistent access to attributes.columns
=> Release v1.3.4

src/Code.gs, src/controllers/timeReport.gs, src/debug.gs, src/jiraCommon.gs, src/models/jira/JiraFilter.gs, src/userManager.gs, src/views/dialogs/createTimeReport.html, src/views/dialogs/whatsNew.html, src/views/sidebar/settings.html
fix/apply compatibility patch for different API responses regarding username vs name vs accountId
=> BugFix 1.4.4

src/Code.gs, src/Storage.gs, src/models/gas/UserStorage.gs, src/models/jira/CustomFields.gs, src/models/jira/IssueFields.gs, src/settings.gs, test/Code.test.js, test/controllers/customFields.test.js, test/controllers/jiraFieldMap.test.js, test/jiraUpdateIssue.test.js, test/jsLib.test.js, test/mocks/PropertiesService.js, test/models/gas/UserStorage.test.js, test/models/jira/IssueFields.test.js
=> #255 merge develop into master

src/Code.gs, src/customFunctions.gs, src/debug.gs, src/jiraApi.gs, src/jiraCommon.gs, test/customFunctions.test.js
=> Merge into Master

src/Code.gs, src/controllers/insertIssueTable.gs, src/models/IssueTableIndex.gs, src/models/jira/IssueFields.gs, src/views/dialogs/insertIssueFromFilter.html
=> v1.4.8 - BugFix
